apiVersion: apps/v1
kind: Deployment
metadata:
  name: mixed-workload
  labels:
    app: mixed-workload
spec:
  replicas: 6
  selector:
    matchLabels:
      app: mixed-workload
  template:
    metadata:
      labels:
        app: mixed-workload
    spec:
      # This deployment can run on any node type
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: node-type
                operator: In
                values: ["spot"]
          - weight: 50
            preference:
              matchExpressions:
              - key: node-type
                operator: In
                values: ["arm64"]
          - weight: 25
            preference:
              matchExpressions:
              - key: node-type
                operator: In
                values: ["x86"]
      tolerations:
      - key: karpenter.sh/capacity-type
        operator: Equal
        value: spot
        effect: NoSchedule
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: mixed-workload-service
spec:
  selector:
    app: mixed-workload
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
