apiVersion: apps/v1
kind: Deployment
metadata:
  name: x86-workload
  labels:
    app: x86-workload
spec:
  replicas: 3
  selector:
    matchLabels:
      app: x86-workload
  template:
    metadata:
      labels:
        app: x86-workload
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
        node-type: x86
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: x86-workload-service
spec:
  selector:
    app: x86-workload
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
